// src/components/charts/LineChart.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useChartRenderer, useZoomPan, buildViewRange, sampleForDisplay } from '@/composables/useChartRenderer'
import { clearCanvas, drawGrid, drawLineSeries, computeXTicks, computeYTicks } from '@/lib/canvasUtils'
import type { RenderContext, DataPoint } from '@/lib/types'
import type { SERIES_CONFIGS } from '@/lib/dataGenerator'

const props = withDefaults(defineProps<{
  data:      DataPoint[]
  series:    (typeof SERIES_CONFIGS[number])[]
  title?:    string
  filled?:   boolean
  height?:   number
}>(), { title: 'Line Chart', filled: true, height: 280 })

const canvasRef = ref<HTMLCanvasElement | null>(null)

const visibleSeriesIds = computed(() => new Set(props.series.map(s => s.id)))
const filteredData     = computed(() => props.data.filter(pt => visibleSeriesIds.value.has(pt.seriesId)))
const baseViewRange    = computed(() => buildViewRange(filteredData.value))

// Stable render function ref so RAF loop always calls the latest version
const renderFnRef = ref<(rc: RenderContext) => void>(() => {})

const { markDirty } = useChartRenderer(canvasRef, renderFnRef)
const { zoom, zoomedViewRange, resetZoom } = useZoomPan(canvasRef, baseViewRange, markDirty)

const viewRange = computed(() => zoomedViewRange())
const xTicks    = computed(() => computeXTicks(viewRange.value, 5))
const yTicks    = computed(() => computeYTicks(viewRange.value, 5))
const canvasH   = computed(() => props.height - 45)
const PADDING   = { top: 40, right: 30, bottom: 50, left: 65 }

function renderChart(rc: RenderContext) {
  rc.viewRange = viewRange.value
  clearCanvas(rc)
  const sampled = sampleForDisplay(filteredData.value, rc.plotWidth * 2)
  const xt = computeXTicks(viewRange.value, 5)
  const yt = computeYTicks(viewRange.value, 5)
  drawGrid(rc, xt, yt)
  for (const s of props.series) {
    const pts = sampled.filter(pt => pt.seriesId === s.id)
    if (pts.length < 2) continue
    drawLineSeries(rc, pts, s.color, 2, props.filled)
  }
}

// Keep render fn ref up-to-date and mark dirty on data changes
watch([filteredData, viewRange, () => props.series, () => props.filled], () => {
  renderFnRef.value = renderChart
  markDirty()
}, { immediate: true })
</script>

<template>
  <div class="chart-container" :style="{ height: `${height}px` }">
    <div class="chart-header">
      <span class="text-sm font-semibold">{{ title }}</span>
      <div class="flex items-center gap-2">
        <button v-if="zoom.scale !== 1" class="btn btn-xs btn-ghost" @click="resetZoom">
          ↺ {{ zoom.scale.toFixed(1) }}×
        </button>
        <span class="badge badge-indigo">{{ filteredData.length.toLocaleString() }} pts</span>
      </div>
    </div>
    <div class="chart-canvas-wrapper" :style="{ height: `${canvasH}px`, position: 'relative' }">
      <canvas ref="canvasRef" style="width:100%;height:100%" />
      <!-- SVG overlay for axis labels (Canvas + SVG hybrid) -->
      <svg
        style="position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;overflow:visible"
        viewBox="0 0 100 100"
        preserveAspectRatio="none"
      >
        <text
          v-for="(t, i) in xTicks"
          :key="`x-${i}`"
          :x="`${(PADDING.left / 800 + t.position * (1 - (PADDING.left + PADDING.right) / 800)) * 100}%`"
          y="96%"
          text-anchor="middle"
          fill="rgba(255,255,255,0.5)"
          font-size="2.5"
          font-family="var(--font-sans)"
        >{{ t.label }}</text>
        <text
          v-for="(t, i) in yTicks"
          :key="`y-${i}`"
          x="1%"
          :y="`${(PADDING.top / canvasH + t.position * (1 - (PADDING.top + 50) / canvasH)) * 100}%`"
          text-anchor="start"
          dominant-baseline="middle"
          fill="rgba(255,255,255,0.5)"
          font-size="2.5"
          font-family="var(--font-mono)"
        >{{ t.label }}</text>
      </svg>
    </div>
  </div>
</template>

// components/charts/LineChart.tsx
'use client';

import React, { useRef, useCallback, useMemo } from 'react';
import { useChartRenderer, useZoomPan, buildViewRange, sampleForDisplay } from '@/hooks/useChartRenderer';
import {
  clearCanvas, drawGrid, drawLineSeries,
  computeXTicks, computeYTicks,
} from '@/lib/canvasUtils';
import type { RenderContext, DataPoint, ViewRange } from '@/lib/types';
import type { SERIES_CONFIGS } from '@/lib/dataGenerator';

interface LineChartProps {
  data: DataPoint[];
  series: (typeof SERIES_CONFIGS[number])[];
  title?: string;
  filled?: boolean;
  height?: number;
}

function LineChart({ data, series, title = 'Line Chart', filled = true, height = 280 }: LineChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const visibleSeriesIds = useMemo(() => new Set<string>(series.map(s => s.id)), [series]);
  const filteredData     = useMemo(
    () => data.filter(pt => visibleSeriesIds.has(pt.seriesId)),
    [data, visibleSeriesIds],
  );
  const baseViewRange = useMemo(() => buildViewRange(filteredData), [filteredData]);

  // Render function (passed to useChartRenderer)
  const renderRef = useRef<(rc: RenderContext) => void>(() => {});

  const { markDirty } = useChartRenderer(canvasRef, (rc) => renderRef.current(rc), [filteredData, series]);

  // Zoom + Pan
  const { zoom, zoomedViewRange, resetZoom } = useZoomPan(canvasRef, baseViewRange, markDirty);
  const viewRange = zoomedViewRange();

  // SVG axis data
  const xTicks = useMemo(() => computeXTicks(viewRange, 5), [viewRange]);
  const yTicks = useMemo(() => computeYTicks(viewRange, 5), [viewRange]);

  // Canvas render
  renderRef.current = useCallback((rc: RenderContext) => {
    rc.viewRange = viewRange;
    clearCanvas(rc);

    const sampled = sampleForDisplay(filteredData, rc.plotWidth * 2);
    const xt = computeXTicks(viewRange, 5);
    const yt = computeYTicks(viewRange, 5);

    drawGrid(rc, xt, yt);

    for (const s of series) {
      const pts = sampled.filter(pt => pt.seriesId === s.id);
      if (pts.length < 2) continue;
      drawLineSeries(rc, pts, s.color, 2, filled);
    }
  }, [filteredData, viewRange, series, filled]);

  // Mark dirty when viewRange changes from zoom/pan
  useMemo(() => { markDirty(); }, [viewRange, markDirty]);

  const PADDING = { top: 40, right: 30, bottom: 50, left: 65 };
  const canvasH = height - 45;

  return (
    <div className="chart-container" style={{ height }}>
      <div className="chart-header">
        <span className="text-sm font-semibold">{title}</span>
        <div className="flex items-center gap-2">
          {zoom.scale !== 1 && (
            <button className="btn btn-xs btn-ghost" onClick={resetZoom}>
              ↺ {zoom.scale.toFixed(1)}×
            </button>
          )}
          <span className="badge badge-indigo">{filteredData.length.toLocaleString()} pts</span>
        </div>
      </div>
      <div className="chart-canvas-wrapper" style={{ height: canvasH, position: 'relative' }}>
        <canvas ref={canvasRef} style={{ width: '100%', height: '100%' }} />
        {/* SVG Overlay for axes (hybrid Canvas+SVG) */}
        <svg
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            pointerEvents: 'none',
            overflow: 'visible',
          }}
          viewBox={`0 0 100 100`}
          preserveAspectRatio="none"
        >
          {/* X axis labels */}
          {xTicks.map((t, i) => {
            const xPct = (PADDING.left / 800 + t.position * (1 - (PADDING.left + PADDING.right) / 800)) * 100;
            return (
              <text
                key={`x-${i}`}
                x={`${xPct}%`}
                y="96%"
                textAnchor="middle"
                fill="rgba(255,255,255,0.5)"
                fontSize="2.5"
                fontFamily="var(--font-sans)"
              >
                {t.label}
              </text>
            );
          })}
          {/* Y axis labels */}
          {yTicks.map((t, i) => {
            const yPct = (PADDING.top / canvasH + t.position * (1 - (PADDING.top + PADDING.bottom) / canvasH)) * 100;
            return (
              <text
                key={`y-${i}`}
                x="1%"
                y={`${yPct}%`}
                textAnchor="start"
                dominantBaseline="middle"
                fill="rgba(255,255,255,0.5)"
                fontSize="2.5"
                fontFamily="var(--font-mono)"
              >
                {t.label}
              </text>
            );
          })}
        </svg>
      </div>
    </div>
  );
}

export default React.memo(LineChart);
