// components/Dashboard.tsx
'use client';

import React, { useMemo } from 'react';
import { useData } from '@/components/providers/DataProvider';
import { SERIES_CONFIGS } from '@/lib/dataGenerator';

import FilterPanel          from '@/components/controls/FilterPanel';
import TimeRangeSelector    from '@/components/controls/TimeRangeSelector';
import LineChart            from '@/components/charts/LineChart';
import BarChart             from '@/components/charts/BarChart';
import ScatterPlot          from '@/components/charts/ScatterPlot';
import Heatmap              from '@/components/charts/Heatmap';
import DataTable            from '@/components/ui/DataTable';
import PerformanceMonitor   from '@/components/ui/PerformanceMonitor';

// ─── Component ────────────────────────────────────────────────────────────────

export default function DashboardClient() {
  const {
    data,
    filters,
    setFilters,
    setTimeRange,
    isStreaming,
    isPaused,
    togglePause,
    toggleStream,
    reset,
    metrics,
  } = useData();

  // Visible series configs
  const visibleSeries = useMemo(
    () => SERIES_CONFIGS.filter(s => filters.visibleSeries.includes(s.id)),
    [filters.visibleSeries],
  );

  return (
    <div className="dashboard-root">
      {/* ── Header ── */}
      <header className="dashboard-header">
        <div className="logo">
          <div className="logo-icon">⚡</div>
          <span>PerfDash</span>
          <span className="text-muted text-sm" style={{ fontWeight: 400 }}>
            — Real-time Data Visualization
          </span>
        </div>

        <div className="flex items-center gap-3">
          {/* Live indicator */}
          {isStreaming && !isPaused && (
            <div className="flex items-center gap-2">
              <div className="live-dot" />
              <span className="text-xs text-secondary">LIVE</span>
            </div>
          )}

          <TimeRangeSelector timeRange={filters.timeRange} onChange={setTimeRange} />

          <button
            id="btn-pause"
            className={`btn btn-sm ${isPaused ? 'btn-primary' : 'btn-ghost'}`}
            onClick={togglePause}
          >
            {isPaused ? '▶ Resume' : '⏸ Pause'}
          </button>

          <button
            id="btn-stream"
            className={`btn btn-sm ${isStreaming ? 'btn-danger' : 'btn-primary'}`}
            onClick={toggleStream}
          >
            {isStreaming ? '⏹ Stop' : '▶ Start'}
          </button>

          <button id="btn-reset" className="btn btn-ghost btn-sm" onClick={reset}>
            ↺ Reset
          </button>
        </div>
      </header>

      {/* ── Body ── */}
      <div className="dashboard-body">
        <FilterPanel filters={filters} onChange={setFilters} />

        <main className="main-content">
          {/* Performance Monitor */}
          <PerformanceMonitor metrics={metrics} />

          {/* Charts Grid */}
          <div className="charts-grid">
            <LineChart
              data={data}
              series={visibleSeries}
              title="Line Chart — Time Series"
              filled
              height={300}
            />
            <BarChart
              data={data}
              series={visibleSeries}
              title="Bar Chart — Aggregated"
              height={300}
              granularity={filters.granularity}
            />
            <ScatterPlot
              data={data}
              series={visibleSeries}
              title="Scatter Plot"
              height={300}
              pointRadius={3}
            />
            <Heatmap
              data={data}
              title="Heatmap — Series × Time"
              height={300}
              granularity={filters.granularity}
            />
          </div>

          {/* Data Table */}
          <DataTable data={data} />
        </main>
      </div>
    </div>
  );
}

// src/components/Dashboard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useDataStore } from '@/stores/dataStore'
import { SERIES_CONFIGS } from '@/lib/dataGenerator'
import FilterPanel        from '@/components/controls/FilterPanel.vue'
import TimeRangeSelector  from '@/components/controls/TimeRangeSelector.vue'
import LineChart          from '@/components/charts/LineChart.vue'
import BarChart           from '@/components/charts/BarChart.vue'
import ScatterPlot        from '@/components/charts/ScatterPlot.vue'
import Heatmap            from '@/components/charts/Heatmap.vue'
import DataTable          from '@/components/ui/DataTable.vue'
import PerformanceMonitor from '@/components/ui/PerformanceMonitor.vue'

const store = useDataStore()

const visibleSeries = computed(() =>
  SERIES_CONFIGS.filter(s => store.filters.visibleSeries.includes(s.id))
)
</script>

<template>
  <div class="dashboard-root">
    <!-- Header -->
    <header class="dashboard-header">
      <div class="logo">
        <div class="logo-icon">⚡</div>
        <span>PerfDash</span>
        <span class="text-muted text-sm" style="font-weight:400">— Real-time Data Visualization</span>
      </div>
      <div class="flex items-center gap-3">
        <div v-if="store.isStreaming && !store.isPaused" class="flex items-center gap-2">
          <div class="live-dot" />
          <span class="text-xs text-secondary">LIVE</span>
        </div>
        <TimeRangeSelector
          :time-range="store.filters.timeRange"
          @change="store.setTimeRange"
        />
        <button
          id="btn-pause"
          :class="`btn btn-sm ${store.isPaused ? 'btn-primary' : 'btn-ghost'}`"
          @click="store.togglePause"
        >{{ store.isPaused ? '▶ Resume' : '⏸ Pause' }}</button>
        <button
          id="btn-stream"
          :class="`btn btn-sm ${store.isStreaming ? 'btn-danger' : 'btn-primary'}`"
          @click="store.toggleStream"
        >{{ store.isStreaming ? '⏹ Stop' : '▶ Start' }}</button>
        <button id="btn-reset" class="btn btn-ghost btn-sm" @click="store.resetData">↺ Reset</button>
      </div>
    </header>

    <!-- Body -->
    <div class="dashboard-body">
      <FilterPanel />

      <main class="main-content">
        <PerformanceMonitor :metrics="store.metrics" />

        <div class="charts-grid">
          <LineChart
            :data="store.data"
            :series="visibleSeries"
            title="Line Chart — Time Series"
            :filled="true"
            :height="300"
          />
          <BarChart
            :data="store.data"
            :series="visibleSeries"
            title="Bar Chart — Aggregated"
            :height="300"
            :granularity="store.filters.granularity"
          />
          <ScatterPlot
            :data="store.data"
            :series="visibleSeries"
            title="Scatter Plot"
            :height="300"
            :point-radius="3"
          />
          <Heatmap
            :data="store.data"
            title="Heatmap — Series × Time"
            :height="300"
            :granularity="store.filters.granularity"
          />
        </div>

        <DataTable :data="store.data" />
      </main>
    </div>
  </div>
</template>
